// Generate src/lib/modelCatalog/catalog.bundled.js from the live models.dev
// catalog, using the app's own sync + build() logic. Run:
//   node --import ./scripts/register.mjs scripts/gen-catalog.mjs
// The bundled snapshot is the cold-start fallback on serverless (where DATA_DIR
// is ephemeral); the daily cron refreshes the live file at runtime.
import fs from "node:fs";
import path from "node:path";

const outDir = path.resolve("tmp/cataloggen");
fs.rmSync(outDir, { recursive: true, force: true });
process.env.DATA_DIR = outDir;

const { syncModelCatalog } = await import("../src/lib/modelCatalog/sync.js");
const res = await syncModelCatalog();
if (!res) throw new Error("sync returned null (models.dev unreachable?)");

const src = path.join(outDir, "model-catalog.json");
const out = "open-sse/providers/catalog.bundled.js";
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out,
  "// Generated by scripts/gen-catalog.mjs — build-time snapshot of models.dev.\n" +
  "// Used as a fallback when DATA_DIR (ephemeral on serverless) has no synced catalog.\n" +
  "export default " + fs.readFileSync(src, "utf8") + ";\n");
console.log("wrote", out, fs.statSync(out).size, "bytes;", JSON.stringify(res));
