// Generate src/lib/db/sql-wasm.b64.js from node_modules/sql.js/dist/sql-wasm.wasm.
// The wasm is inlined so the serverless function needs NO fs/wasm-file lookup —
// immune to Next file-tracing gaps (sql.js is a serverExternalPackage and its
// wasm is read dynamically, which tracing misses).
import fs from "node:fs";

const wasm = fs.readFileSync("node_modules/sql.js/dist/sql-wasm.wasm");
const b64 = wasm.toString("base64");
const out = "src/lib/db/sql-wasm.b64.js";
fs.writeFileSync(out,
  "// Generated by scripts/gen-sqlwasm.mjs from node_modules/sql.js/dist/sql-wasm.wasm.\n" +
  "// Inlined so the serverless function needs no fs/wasm-file lookup (tracing-proof).\n" +
  "export default " + JSON.stringify(b64) + ";\n");
console.log("wrote", out, b64.length, "chars (wasm", wasm.length, "bytes)");
